version: '3.4'

services:
  abi-rabbit:
    ports:
     - "5672:5672"
     - "8086:15672"    
    volumes:
     - /var/lib/rabbitmq
    image: rabbitmq:3-management
  masstransitmultistepsaga:
    image: masstransitmultistepsaga
    build:
      context: .
      dockerfile: MassTransit.MultiStep.Saga/Dockerfile
  masstransitmultistepcreditservice:
    image: masstransitmultistepcreditservice
    build:
      context: .
      dockerfile: MassTransit.MultiStep.CreditService/Dockerfile      
  masstransitmultistepapi:
    ports:
     - "8181:80"
    image: masstransitmultistepapi
    build:
      context: .
      dockerfile: MassTransit.MultiStep.Api/Dockerfile
  masstransitmultistepportal:
    image: masstransitmultistepportal
    build:
      context: .
      dockerfile: MassTransit.MultiStep.Portal/Dockerfile
  masstransitmultistepangular:
    ports:
     - "32770:80"
     - "4200:4200"
     - "4201:4201"
    image: masstransitmultistepangular
    build:
      context: .
      dockerfile: MassTransit.MultiStep.Angular/Dockerfile